NEONS_LIST = {
    "coronet1",
    "creshez",
    "creshez5",
    "creshez6",
    "creshez8",
    "creshez10",
    "creshez11",
    "creshez12",
    "creshez14",
    "creshez15",
    "creshez16",
    "creshez17",
    "creshez18",
    "creshez20",
    "creshez21",
    "creshez22",
    "creshez23",
    "creshez24",
    "creshez25",
    "creshez26",
    "creshez28",
    "creshez29",
    "dlf1",
    "dlf3",
    "dlf5",
    "dlf8",
    "dlf10",
    "dlf11",
    "dlf12",
    "dlf13",
    "dlf15",
    "dlf17",
    "dlf18",
    "dlf19",
    "dlf26",
    "dlf29",
    "dlf31",
    "dlf43",
    "dlf44",
    "docko1",
    "docko3",
    "flame",
    "gallardo",
    "gallardo1",
    "gallardo2",
    "gallardo4",
    "gallardo5",
    "lines",
    "mirage1",
    "mirage5",
    "mirage6",
    "mirage10",
    "mirage11",
    "puni1",
    "saky4",
    "senya1",
    "spectrum",
    "spitfire4",
    "spitfire7",
    "spitfire9",
    "spitfire17",
    "spitfire18",
    "spitfire19",
    "spitfire20",
    "spitfire22",
    "spitfire23",
    "spitfire24",
    "tremor3",
    "tremor5",
}

NEONS_ENG_NAMES = {
    "star_regiment",
    "drowning",
    "neurons",
    "cyber_​​download",
    "silence_of_sounds",
    "joy_of_trip",
    "bright_target",
    "green_unrestrained",
    "brightness_of_moment",
    "out_of_matrix",
    "howling_redemption",
    "cyber_​​attack",
    "long_trip",
    "difficulty_of_choice",
    "bloody_dream",
    "space_star",
    "data_transfer",
    "fall",
    "return",
    "cycle",
    "ussr",
    "bmw",
    "dissolution",
    "tenderness",
    "incredible_bit",
    "crazy_hypnosis",
    "gravestone_youth",
    "summer_happiness",
    "only_forward",
    "blinding_fall",
    "road_to_distance",
    "electro",
    "net",
    "town",
    "leader_structure",
    "love_story",
    "card_passion",
    "huge_pixels",
    "stars",
    "long_term_simple",
    "mazda",
    "living_fire",
    "blue_neon",
    "red_neon",
    "yellow_neon",
    "stylish_70s",
    "neon_stripes",
    "maze",
    "dubstep",
    "unprincipled_style",
    "rorshech_is_over",
    "flower_happiness",
    "pink_dreams",
    "swords",
    "arm",
    "neon_spiral",
    "far_away",
    "holiday_balls",
    "endless_love",
    "music_in_blood",
    "rainbow_path",
    "neon_flame",
    "cure_for_soullessness",
    "particle_explosion",
    "on_wave",
    "neon_path",
    "x_space",
    "monster",
    "blue_flame",
}

NEONS_RU_NAMES = {
    "Звездный полк",
    "Утопление",
    "Нейроны",
    "Кибер загрузка",
    "Молчания звуков",
    "Радость поездки",
    "Яркая цель",
    "Зеленая безудержность",
    "Яркость момента",
    "Запределами матрицы",
    "Воющие иступление",
    "Кибер атака",
    "Продолжительная поездка",
    "Сложность выбора",
    "Кровавая мечта",
    "Космическая звезда",
    "Передача данных",
    "Осень",
    "Возвращение",
    "Цикл",
    "СССР",
    "BMW",
    "Растворение",
    "Нежность",
    "Невероятный бит",
    "Сумашедший гипноз",
    "Надгробная молодость",
    "Летнее счастье",
    "Только вперед",
    "Слепящие падение",
    "Дорога в даль",
    "Электро",
    "Сеть",
    "Город",
    "Структура лидера",
    "Любовная история",
    "Карточная страсть",
    "Огромные пиксели",
    "Звезды",
    "Длительная простота",
    "Mazda",
    "Живой огонь",
    "Синий неон",
    "Красный неон",
    "Желтый неон",
    "Стильные 70-е",
    "Неоновые полосы",
    "Лабиринт",
    "Дабстеп",
    "Безпринципный стиль",
    "Роршех кончился",
    "Цветочное счастье",
    "Розовые мечты",
    "Мечи",
    "Рука",
    "Неоновая спираль",
    "Далекие дали",
    "Прадзничные шары",
    "Безграничная любовь",
    "Музыка в крови",
    "Радужный путь",
    "Неоновое пламя",
    "Лекарство бездушия",
    "Взрыв частиц",
    "На волне",
    "Неоновый путь",
    "Икс космос",
    "Монстер",
    "Синие пламя",
}