CONST_WALLPAPER =
{
    { name = "BMW",          img = "bmw",        price = 50,   currency = "hard", fontColor = 0xFFFFFFFF },    
    { name = "Ночной город", img = "night_city", price = 25,   currency = "hard", fontColor = 0xFFFFFFFF },    
    { name = "Дорога",       img = "road",       price = 35,   currency = "hard", fontColor = 0xFFFFFFFF },    
    { name = "Дым",          img = "smoke",      price = 1500, currency = "soft", fontColor = 0xFFFFFFFF },    
    { name = "Капюшон",      img = "hood",       price = 30,   currency = "hard", fontColor = 0xFFFFFFFF },    
    { name = "Космос",       img = "cosmos",     price = 20,   currency = "hard", fontColor = 0xFFFFFFFF },    
    { name = "Взрыв красок", img = "colors",     price = 1500, currency = "soft", fontColor = 0xFFFFFFFF },    
    { name = "Крыша",        img = "roof",       price = 2000, currency = "soft", fontColor = 0xFFFFFFFF },    
    { name = "Море штиль",   img = "calmsea",    price = 1500, currency = "soft", fontColor = 0xFFFFFFFF },    
    { name = "Nissan GTR",   img = "nissan",     price = 1200, currency = "soft", fontColor = 0xFFFFFFFF },    
    { name = "Пальма",       img = "palm",       price = 1300, currency = "soft", fontColor = 0xFFFFFFFF },    
    { name = "Пристань",     img = "pier",       price = 1200, currency = "soft", fontColor = 0xFFFFFFFF },    
    { name = "Стена",        img = "wall",       price = 1000, currency = "soft", fontColor = 0xFFFFFFFF },    
    { name = "Стиль",        img = "style",      price = 2000, currency = "soft", fontColor = 0xFFFFFFFF },    
    { name = "Цветок",       img = "flower",     price = 1400, currency = "soft", fontColor = 0xFFFFFFFF },    
    { name = "Bosow",        img = "bosow", },
    { name = "Бестик",       img = "bestik_1", },        
}