WEDDING_FOOD_COOKING_DISCOUNT = 10
WEDDING_FOOD_COOKING_DISCOUNT_ENABLED = true

WEDDING_EXP_BOOST_ENABLED = true
WEDDING_EXP_BOOST = 20
WEDDING_EXP_BOOST_DISTANCE = 100

WEDDING_SINGLE_GENDER = false
WEDDING_USE_BOTH_APART = true
WEDDING_USE_BOTH_GARAGE = true
WEDDING_USE_BOTH_BED = true
WEDDING_USE_BOTH_WARDROBE = true
WEDDING_USE_BOTH_COOKING = true

WEDDING_SKINS = {
    male = 267,
    female = 264,
    preist = 268,
};

WEDDING_SKINS_DURABLE = 2 * 24 * 60 * 60
PAYMENTS_RELEASE_DATE = 1586986200