NEON_REMOVAL_LIST = { 
    "__snow",
    "tr_kedr*", "kedr", "tree*", "ccc", "der_nw",
    "smoke*", "environ", "port_cargo",
    "smokeex",
    "univer_detail_1",
    "stvol", "bereza",
    "post1", "post_c_1", "trafllig_1",
    "vishka_01",
    "detail_land", "detail_land2", "det_land",
    "newfx*", "detail_3", "detail_park", "park_detail", 
    "tp_map", "sosna", "gen_log", "house_map_2",
    "", "*spoiler*", "*particle*", "*light*",
    "vehicle*", "?emap*", "?hite*",
    "*92*", "*wheel*", "*interior*",
    "*handle*", "*body*", "*decal*",
    "*8bit*", "*logos*", "*badge*",
    "*plate*", "*sign*",
    "*headlight*",
    "*shad*",
    "coronastar",
    "tx*",
    "lod*",
    "cj_w_grad",
    "*cloud*",
    "*smoke*",
    "sphere_cj",
    "particle*",
    "*water*", "coral",
    "shpere", "*inferno*", "*fire*", "*cypress*","list",
    "*brtb*","*tree*","*leave*","*spark*","*eff*","*branch","*ash*","*fire*","*rocket*","*hud*",
    "bark2","bchamae","*sfx*","*wires*","*agave*","*plant*","neon","*log*",
    "sjmshopbk",
    --"*sand*",
    "*radar*",
    "*skybox*",
    "metalox64","metal1_128",
    "nitro","repair","carchange",
    "bullethitsmoke",
    "toll_sfw1","toll_sfw3","trespasign1_256","steel64","beachwalkway","ws_greymeta","telepole2128","ah_barpanelm",
    "plasticdrum1_128","planks01","unnamed","aascaff128",
}